//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostAccounting.Model_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balances
    {
        public int Id { get; set; }
        public Nullable<double> Sum { get; set; }
        public int Type { get; set; }
        public Nullable<int> IdAnalytic { get; set; }
        public Nullable<int> IdArticle { get; set; }
    
        public virtual Analytics Analytics { get; set; }
        public virtual Articles Articles { get; set; }
    }
}
