//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostAccounting.Model_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costs
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public double Sum { get; set; }
        public string Message { get; set; }
        public int IdAnalytic { get; set; }
        public int IdArticle { get; set; }
    
        public virtual Analytics Analytics { get; set; }
        public virtual Articles Articles { get; set; }
    }
}
